defaults:
  - data: default
  - preprocessing: default
  - model: default
  - training: default
  - inference: default
  - postprocessing: default
  - dvc: default
  - logging: train
  - _self_

paths:
  project_root: .
  data_dir: data
  checkpoint_path: artifacts/flood_model.ckpt

hydra:
  run:
    dir: .
  output_subdir: null
